### ISSUE TITLE
Realizar modelagem de dados para entidades do projeto

### ISSUE THREAD

**Issue by lumamontes** [terceiro-setor-opensource/mba-full-08-grupo-02#4]
### Descrição

Realizar modelagem de dados para entidades do projeto: Usuários, Locais, Esportes

### Objetivo

Criar modelagem de dados com base no layout fornecido do Figma. A  modelagem deve incluir relacionamentos, atributos e tipos de dados adequados para as funcionalidades

### Critérios de aceitação 

- Entidades bem definidas com atributos apropriados.
- Relacionamentos claros entre as entidades.
- Adicionar no Miro para facilitar a visualização/colaboração

**Comment by robertalxa** [comment]
Modelagem definida e aceita pelo grupo no dia 06/08/24, de acordo com o modelo a seguir:


![Image](https://github.com/user-attachments/assets/1a9f913c-a65a-4541-b9d1-f4c86e693af0)

**Comment by robertalxa** [comment]
Modelagem definida e aceita pelo grupo no dia 06/08/24, de acordo com o modelo a seguir:
![image](https://github.com/user-attachments/assets/1e1bb08c-03be-4238-84cb-5d75d1272023)
